### ISSUE TITLE
hid

### ISSUE THREAD

**Issue by laszewsk** [cybertraining-dsc/fa20-523-316#1]
you can not hae two authors with the same hid. please correct

**Comment by ngsudheer** [comment]
@laszewsk Professor, we both are doing the project. You assigned both of us as owners.

**Comment by laszewsk** [comment]
the report has a place for  the author name, each author is followed by each authors hid. please correct this. you can not have both the same hid.

the paper is only in one hid.

also fill out the README.yaml. use 301 or 312 as a template how to do that. This will be assigned soon

**Comment by laszewsk** [comment]
i fixed the report and the readme for you
